-- =====================================================================================================
--  MISSION CONTROL - cơ sở dữ liệu PostgreSQL
--  Chạy MỘT LẦN trên database trống (và chạy lại bao nhiêu lần cũng an toàn: file này không xóa gì).
--
--  Cách chạy:
--    * Railway / Render / Neon / Supabase: mở "SQL Editor" (hoặc tab Query của Postgres), dán toàn bộ file này, bấm Run.
--    * Dòng lệnh:  psql "$DATABASE_URL" -f sql/schema.sql
--
--  Gồm 4 phần:  1) tạo bảng   2) nâng cấp từ bản cũ   3) CẤP QUYỀN ADMIN (sửa 1 dòng email)   4) kiểm tra nhanh
--  Ứng dụng cũng tự tạo bảng còn thiếu khi khởi động; file này dành cho bạn muốn tạo sẵn và kiểm soát cấu trúc.
-- =====================================================================================================


-- ============================ 1) TẠO BẢNG ===========================================================

-- Tài khoản. Mật khẩu chỉ lưu dạng BĂM một chiều (password_hash), không ai đọc lại được, kể cả admin.
CREATE TABLE IF NOT EXISTS users (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name       VARCHAR(80)  NOT NULL,
    email              VARCHAR(254) NOT NULL,                       -- luôn chữ thường
    password_hash      VARCHAR(255) NOT NULL,
    role               VARCHAR(10)  NOT NULL DEFAULT 'user'    CHECK (role   IN ('user', 'admin')),
    status             VARCHAR(10)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'disabled')),
    created_at         TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    decided_at         TIMESTAMP,
    reset_hash         VARCHAR(255),                                -- mật khẩu MỚI (đã băm) đang chờ admin duyệt
    reset_requested_at TIMESTAMP,
    auth_ver           INTEGER      NOT NULL DEFAULT 0              -- tăng mỗi lần đổi mật khẩu -> đăng xuất mọi phiên cũ
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

-- Mỗi người một cấu hình LLM. api_key_enc là bản MÃ HÓA (khóa chủ MASTER_KEY nằm ở biến môi trường, KHÔNG nằm trong database).
CREATE TABLE IF NOT EXISTS user_settings (
    user_id     INTEGER PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    api_key_enc TEXT,
    base_url    VARCHAR(300),
    model       VARCHAR(200),
    updated_at  TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

-- Lịch sử: chỉ lưu những phân tích ĐÃ DUYỆT xong. Phân tích đang dở nằm trong RAM và mất nếu không duyệt.
CREATE TABLE IF NOT EXISTS analyses (
    id           VARCHAR(16) PRIMARY KEY,
    user_id      INTEGER   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    question     TEXT,
    ctx          TEXT,
    title        TEXT,
    report_title TEXT,
    started      VARCHAR(32),
    finished     VARCHAR(32),
    sources      JSON,
    files        JSON,
    has_snap     BOOLEAN   DEFAULT FALSE,
    snapshot     JSON,
    created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS ix_analyses_user_id    ON analyses (user_id);
CREATE INDEX IF NOT EXISTS ix_analyses_created_at ON analyses (created_at);

-- Tệp xuất của từng phân tích (dashboard, báo cáo, PPTX, ZIP...).
CREATE TABLE IF NOT EXISTS analysis_files (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(16)  NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    name        VARCHAR(120) NOT NULL,
    mimetype    VARCHAR(100) NOT NULL,
    data        BYTEA        NOT NULL,
    UNIQUE (analysis_id, name)
);
CREATE INDEX IF NOT EXISTS ix_analysis_files_analysis_id ON analysis_files (analysis_id);


-- ============================ 2) NÂNG CẤP TỪ BẢN CŨ (không có tác dụng nếu bạn vừa tạo mới ở trên) =====
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_hash         VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_requested_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_ver           INTEGER NOT NULL DEFAULT 0;


-- ============================ 3) CẤP QUYỀN ADMIN =====================================================
--  Cách làm:  (a) mở trang web, bấm "Đăng ký" bằng chính email của bạn, tự đặt mật khẩu;
--             (b) sửa email ở dòng "admin_email" bên dưới thành email đó;
--             (c) chạy lại file này (hoặc chỉ khối DO bên dưới).
--  Tài khoản sẽ được duyệt và nâng thành admin ngay. Mật khẩu vẫn do bạn tự đặt, không xuất hiện trong SQL.
--  Có thể cấp cho nhiều người: đổi email rồi chạy lại.
DO $$
DECLARE
    admin_email text := lower(trim('you@gmail.com'));        -- <<<<<< SỬA EMAIL Ở ĐÂY
    n integer;
BEGIN
    IF admin_email = 'you@gmail.com' THEN
        RAISE NOTICE 'Bỏ qua cấp admin: hãy sửa dòng admin_email ở phần 3 thành email của bạn.';
        RETURN;
    END IF;
    UPDATE users
       SET role = 'admin', status = 'approved',
           decided_at = COALESCE(decided_at, now() AT TIME ZONE 'utc'),
           reset_hash = NULL, reset_requested_at = NULL
     WHERE email = admin_email;
    GET DIAGNOSTICS n = ROW_COUNT;
    IF n = 0 THEN
        RAISE NOTICE 'Chưa có tài khoản %. Hãy đăng ký trên web bằng email này trước, rồi chạy lại khối này.', admin_email;
    ELSE
        RAISE NOTICE 'Đã cấp quyền admin cho %.', admin_email;
    END IF;
END $$;

--  Thu hồi quyền admin (bỏ dấu -- ở đầu dòng rồi sửa email):
--  UPDATE users SET role = 'user' WHERE email = 'ten@gmail.com';
--  Admin quên mật khẩu: chạy trên máy chủ  python manage.py set-password ten@gmail.com


-- ============================ 4) KIỂM TRA NHANH (không hiển thị mật khẩu) ============================
SELECT id, display_name, email, role, status, (reset_hash IS NOT NULL) AS dang_cho_dat_lai_mk, created_at
  FROM users ORDER BY id;
